package imSQL

import (
	"database/sql"
	"fmt"

	"github.com/juju/errors"
)

type (
	Variable struct {
		Name    string `json:"Variable_name" db:"Variable_name"`
		Value   string `json:"Value" db:"Value"`
		Dynamic string `json:"Dynamic" db:"Dynamic"`
	}
)

const (
	StmtShowVariables       = `SHOW VARIABLES`
	StmtSetDynamicVariables = `SET GLOBAL %s = %s`
)

var (
	// global or session variables.
	// https://dev.mysql.com/doc/refman/5.7/en/dynamic-system-variables.html
	GlobalDynamicVars = map[string]string{
		"audit_log_connection_policy":                     "audit_log_connection_policy",
		"audit_log_exclude_accounts":                      "audit_log_exclude_accounts",
		"audit_log_flush":                                 "audit_log_flush",
		"audit_log_include_accounts":                      "audit_log_include_accounts",
		"audit_log_rotate_on_size":                        "audit_log_rotate_on_size",
		"audit_log_statement_policy":                      "audit_log_statement_policy",
		"authentication_ldap_sasl_auth_method_name":       "authentication_ldap_sasl_auth_method_name",
		"authentication_ldap_sasl_bind_base_dn":           "authentication_ldap_sasl_bind_base_dn",
		"authentication_ldap_sasl_bind_root_dn":           "authentication_ldap_sasl_bind_root_dn",
		"authentication_ldap_sasl_bind_root_pwd":          "authentication_ldap_sasl_bind_root_pwd",
		"authentication_ldap_sasl_ca_path":                "authentication_ldap_sasl_ca_path",
		"authentication_ldap_sasl_group_search_attr":      "authentication_ldap_sasl_group_search_attr",
		"authentication_ldap_sasl_group_search_filter":    "authentication_ldap_sasl_group_search_filter",
		"authentication_ldap_sasl_init_pool_size":         "authentication_ldap_sasl_init_pool_size",
		"authentication_ldap_sasl_log_status":             "authentication_ldap_sasl_log_status",
		"authentication_ldap_sasl_max_pool_size":          "authentication_ldap_sasl_max_pool_size",
		"authentication_ldap_sasl_server_host":            "authentication_ldap_sasl_server_host",
		"authentication_ldap_sasl_server_port":            "authentication_ldap_sasl_server_port",
		"authentication_ldap_sasl_tls":                    "authentication_ldap_sasl_tls",
		"authentication_ldap_sasl_user_search_attr":       "authentication_ldap_sasl_user_search_attr",
		"authentication_ldap_simple_auth_method_name":     "authentication_ldap_simple_auth_method_name",
		"authentication_ldap_simple_bind_base_dn":         "authentication_ldap_simple_bind_base_dn",
		"authentication_ldap_simple_bind_root_dn":         "authentication_ldap_simple_bind_root_dn",
		"authentication_ldap_simple_bind_root_pwd":        "authentication_ldap_simple_bind_root_pwd",
		"authentication_ldap_simple_ca_path":              "authentication_ldap_simple_ca_path",
		"authentication_ldap_simple_group_search_attr":    "authentication_ldap_simple_group_search_attr",
		"authentication_ldap_simple_group_search_filter":  "authentication_ldap_simple_group_search_filter",
		"authentication_ldap_simple_init_pool_size":       "authentication_ldap_simple_init_pool_size",
		"authentication_ldap_simple_log_status":           "authentication_ldap_simple_log_status",
		"authentication_ldap_simple_max_pool_size":        "authentication_ldap_simple_max_pool_size",
		"authentication_ldap_simple_server_host":          "authentication_ldap_simple_server_host",
		"authentication_ldap_simple_server_port":          "authentication_ldap_simple_server_port",
		"authentication_ldap_simple_tls":                  "authentication_ldap_simple_tls",
		"authentication_ldap_simple_user_search_attr":     "authentication_ldap_simple_user_search_attr",
		"auto_increment_increment":                        "auto_increment_increment",
		"auto_increment_offset":                           "auto_increment_offset",
		"autocommit":                                      "autocommit",
		"automatic_sp_privileges":                         "automatic_sp_privileges",
		"avoid_temporal_upgrade":                          "avoid_temporal_upgrade",
		"big_tables":                                      "big_tables",
		"binlog_cache_size":                               "binlog_cache_size",
		"binlog_checksum":                                 "binlog_checksum",
		"binlog_direct_non_transactional_updates":         "binlog_direct_non_transactional_updates",
		"binlog_error_action":                             "binlog_error_action",
		"binlog_format":                                   "binlog_format",
		"binlog_group_commit_sync_delay":                  "binlog_group_commit_sync_delay",
		"binlog_group_commit_sync_no_delay_count":         "binlog_group_commit_sync_no_delay_count",
		"binlog_max_flush_queue_time":                     "binlog_max_flush_queue_time",
		"binlog_order_commits":                            "binlog_order_commits",
		"binlog_row_image=image_type":                     "binlog_row_image=image_type",
		"binlog_rows_query_log_events":                    "binlog_rows_query_log_events",
		"binlog_stmt_cache_size":                          "binlog_stmt_cache_size",
		"binlogging_impossible_mode":                      "binlogging_impossible_mode",
		"block_encryption_mode":                           "block_encryption_mode",
		"bulk_insert_buffer_size":                         "bulk_insert_buffer_size",
		"character_set_client":                            "character_set_client",
		"character_set_connection":                        "character_set_connection",
		"character_set_database":                          "character_set_database",
		"character_set_filesystem":                        "character_set_filesystem",
		"character_set_results":                           "character_set_results",
		"character_set_server":                            "character_set_server",
		"check_proxy_users":                               "check_proxy_users",
		"collation_connection":                            "collation_connection",
		"collation_database":                              "collation_database",
		"collation_server":                                "collation_server",
		"completion_type":                                 "completion_type",
		"concurrent_insert":                               "concurrent_insert",
		"connect_timeout":                                 "connect_timeout",
		"connection_control_failed_connections_threshold": "connection_control_failed_connections_threshold",
		"connection_control_max_connection_delay":         "connection_control_max_connection_delay",
		"connection_control_min_connection_delay":         "connection_control_min_connection_delay",
		"default_password_lifetime":                       "default_password_lifetime",
		"default_storage_engine":                          "default_storage_engine",
		"default_tmp_storage_engine":                      "default_tmp_storage_engine",
		"default_week_format":                             "default_week_format",
		"delay_key_write":                                 "delay_key_write",
		"delayed_insert_limit":                            "delayed_insert_limit",
		"delayed_insert_timeout":                          "delayed_insert_timeout",
		"delayed_queue_size":                              "delayed_queue_size",
		"div_precision_increment":                         "div_precision_increment",
		"end_markers_in_json":                             "end_markers_in_json",
		"enforce_gtid_consistency":                        "enforce_gtid_consistency",
		"eq_range_index_dive_limit":                       "eq_range_index_dive_limit",
		"event_scheduler":                                 "event_scheduler",
		"executed_gtids_compression_period":               "executed_gtids_compression_period",
		"expire_logs_days":                                "expire_logs_days",
		"explicit_defaults_for_timestamp":                 "explicit_defaults_for_timestamp",
		"flush":                                              "flush",
		"flush_time":                                         "flush_time",
		"foreign_key_checks":                                 "foreign_key_checks",
		"ft_boolean_syntax":                                  "ft_boolean_syntax",
		"general_log":                                        "general_log",
		"general_log_file":                                   "general_log_file",
		"group_concat_max_len":                               "group_concat_max_len",
		"group_replication_allow_local_disjoint_gtids_join":  "group_replication_allow_local_disjoint_gtids_join",
		"group_replication_allow_local_lower_version_join":   "group_replication_allow_local_lower_version_join",
		"group_replication_auto_increment_increment":         "group_replication_auto_increment_increment",
		"group_replication_bootstrap_group":                  "group_replication_bootstrap_group",
		"group_replication_components_stop_timeout":          "group_replication_components_stop_timeout",
		"group_replication_compression_threshold":            "group_replication_compression_threshold",
		"group_replication_enforce_update_everywhere_checks": "group_replication_enforce_update_everywhere_checks",
		"group_replication_flow_control_applier_threshold":   "group_replication_flow_control_applier_threshold",
		"group_replication_flow_control_certifier_threshold": "group_replication_flow_control_certifier_threshold",
		"group_replication_flow_control_mode":                "group_replication_flow_control_mode",
		"group_replication_force_members":                    "group_replication_force_members",
		"group_replication_group_name":                       "group_replication_group_name",
		"group_replication_group_seeds":                      "group_replication_group_seeds",
		"group_replication_gtid_assignment_block_size":       "group_replication_gtid_assignment_block_size",
		"group_replication_ip_whitelist":                     "group_replication_ip_whitelist",
		"group_replication_local_address":                    "group_replication_local_address",
		"group_replication_member_weight":                    "group_replication_member_weight",
		"group_replication_poll_spin_loops":                  "group_replication_poll_spin_loops",
		"group_replication_recovery_complete_at":             "group_replication_recovery_complete_at",
		"group_replication_recovery_reconnect_interval":      "group_replication_recovery_reconnect_interval",
		"group_replication_recovery_retry_count":             "group_replication_recovery_retry_count",
		"group_replication_recovery_ssl_ca":                  "group_replication_recovery_ssl_ca",
		"group_replication_recovery_ssl_capath":              "group_replication_recovery_ssl_capath",
		"group_replication_recovery_ssl_cert":                "group_replication_recovery_ssl_cert",
		"group_replication_recovery_ssl_cipher":              "group_replication_recovery_ssl_cipher",
		"group_replication_recovery_ssl_crl":                 "group_replication_recovery_ssl_crl",
		"group_replication_recovery_ssl_crlpath":             "group_replication_recovery_ssl_crlpath",
		"group_replication_recovery_ssl_key":                 "group_replication_recovery_ssl_key",
		"group_replication_recovery_ssl_verify_server_cert":  "group_replication_recovery_ssl_verify_server_cert",
		"group_replication_recovery_use_ssl":                 "group_replication_recovery_use_ssl",
		"group_replication_single_primary_mode":              "group_replication_single_primary_mode",
		"group_replication_ssl_mode":                         "group_replication_ssl_mode",
		"group_replication_start_on_boot":                    "group_replication_start_on_boot",
		"group_replication_transaction_size_limit":           "group_replication_transaction_size_limit",
		"group_replication_unreachable_majority_timeout":     "group_replication_unreachable_majority_timeout",
		"gtid_executed_compression_period":                   "gtid_executed_compression_period",
		"gtid_mode":                                          "gtid_mode",
		"gtid_purged":                                        "gtid_purged",
		"host_cache_size":                                    "host_cache_size",
		"init_connect":                                       "init_connect",
		"init_slave":                                         "init_slave",
		"innodb_adaptive_flushing":                           "innodb_adaptive_flushing",
		"innodb_adaptive_flushing_lwm":                       "innodb_adaptive_flushing_lwm",
		"innodb_adaptive_hash_index":                         "innodb_adaptive_hash_index",
		"innodb_adaptive_max_sleep_delay":                    "innodb_adaptive_max_sleep_delay",
		"innodb_api_bk_commit_interval":                      "innodb_api_bk_commit_interval",
		"innodb_api_trx_level":                               "innodb_api_trx_level",
		"innodb_autoextend_increment":                        "innodb_autoextend_increment",
		"innodb_background_drop_list_empty":                  "innodb_background_drop_list_empty",
		"innodb_buffer_pool_dump_at_shutdown":                "innodb_buffer_pool_dump_at_shutdown",
		"innodb_buffer_pool_dump_now":                        "innodb_buffer_pool_dump_now",
		"innodb_buffer_pool_dump_pct":                        "innodb_buffer_pool_dump_pct",
		"innodb_buffer_pool_filename":                        "innodb_buffer_pool_filename",
		"innodb_buffer_pool_load_abort":                      "innodb_buffer_pool_load_abort",
		"innodb_buffer_pool_load_now":                        "innodb_buffer_pool_load_now",
		"innodb_buffer_pool_size":                            "innodb_buffer_pool_size",
		"innodb_change_buffer_max_size":                      "innodb_change_buffer_max_size",
		"innodb_change_buffering":                            "innodb_change_buffering",
		"innodb_change_buffering_debug":                      "innodb_change_buffering_debug",
		"innodb_checksum_algorithm":                          "innodb_checksum_algorithm",
		"innodb_cmp_per_index_enabled":                       "innodb_cmp_per_index_enabled",
		"innodb_commit_concurrency":                          "innodb_commit_concurrency",
		"innodb_compress_debug":                              "innodb_compress_debug",
		"innodb_compression_failure_threshold_pct":           "innodb_compression_failure_threshold_pct",
		"innodb_compression_level":                           "innodb_compression_level",
		"innodb_compression_pad_pct_max":                     "innodb_compression_pad_pct_max",
		"innodb_concurrency_tickets":                         "innodb_concurrency_tickets",
		"innodb_deadlock_detect":                             "innodb_deadlock_detect",
		"innodb_default_row_format":                          "innodb_default_row_format",
		"innodb_disable_resize_buffer_pool_debug":            "innodb_disable_resize_buffer_pool_debug",
		"innodb_disable_sort_file_cache":                     "innodb_disable_sort_file_cache",
		"innodb_fast_shutdown":                               "innodb_fast_shutdown",
		"innodb_fil_make_page_dirty_debug":                   "innodb_fil_make_page_dirty_debug",
		"innodb_file_format":                                 "innodb_file_format",
		"innodb_file_format_max":                             "innodb_file_format_max",
		"innodb_file_per_table":                              "innodb_file_per_table",
		"innodb_fill_factor":                                 "innodb_fill_factor",
		"innodb_flush_log_at_timeout":                        "innodb_flush_log_at_timeout",
		"innodb_flush_log_at_trx_commit":                     "innodb_flush_log_at_trx_commit",
		"innodb_flush_neighbors":                             "innodb_flush_neighbors",
		"innodb_flush_sync":                                  "innodb_flush_sync",
		"innodb_flushing_avg_loops":                          "innodb_flushing_avg_loops",
		"innodb_ft_aux_table":                                "innodb_ft_aux_table",
		"innodb_ft_enable_diag_print":                        "innodb_ft_enable_diag_print",
		"innodb_ft_enable_stopword":                          "innodb_ft_enable_stopword",
		"innodb_ft_num_word_optimize":                        "innodb_ft_num_word_optimize",
		"innodb_ft_result_cache_limit":                       "innodb_ft_result_cache_limit",
		"innodb_ft_server_stopword_table":                    "innodb_ft_server_stopword_table",
		"innodb_ft_user_stopword_table":                      "innodb_ft_user_stopword_table",
		"innodb_io_capacity":                                 "innodb_io_capacity",
		"innodb_io_capacity_max":                             "innodb_io_capacity_max",
		"innodb_large_prefix":                                "innodb_large_prefix",
		"innodb_limit_optimistic_insert_debug":               "innodb_limit_optimistic_insert_debug",
		"innodb_lock_wait_timeout":                           "innodb_lock_wait_timeout",
		"innodb_log_checksum_algorithm":                      "innodb_log_checksum_algorithm",
		"innodb_log_checksums":                               "innodb_log_checksums",
		"innodb_log_compressed_pages":                        "innodb_log_compressed_pages",
		"innodb_log_write_ahead_size":                        "innodb_log_write_ahead_size",
		"innodb_lru_scan_depth":                              "innodb_lru_scan_depth",
		"innodb_max_dirty_pages_pct":                         "innodb_max_dirty_pages_pct",
		"innodb_max_dirty_pages_pct_lwm":                     "innodb_max_dirty_pages_pct_lwm",
		"innodb_max_purge_lag":                               "innodb_max_purge_lag",
		"innodb_max_purge_lag_delay":                         "innodb_max_purge_lag_delay",
		"innodb_max_undo_log_size":                           "innodb_max_undo_log_size",
		"innodb_merge_threshold_set_all_debug":               "innodb_merge_threshold_set_all_debug",
		"innodb_monitor_disable":                             "innodb_monitor_disable",
		"innodb_monitor_enable":                              "innodb_monitor_enable",
		"innodb_monitor_reset":                               "innodb_monitor_reset",
		"innodb_monitor_reset_all":                           "innodb_monitor_reset_all",
		"innodb_old_blocks_pct":                              "innodb_old_blocks_pct",
		"innodb_old_blocks_time":                             "innodb_old_blocks_time",
		"innodb_online_alter_log_max_size":                   "innodb_online_alter_log_max_size",
		"innodb_optimize_fulltext_only":                      "innodb_optimize_fulltext_only",
		"innodb_print_all_deadlocks":                         "innodb_print_all_deadlocks",
		"innodb_purge_batch_size":                            "innodb_purge_batch_size",
		"innodb_purge_rseg_truncate_frequency":               "innodb_purge_rseg_truncate_frequency",
		"innodb_random_read_ahead":                           "innodb_random_read_ahead",
		"innodb_read_ahead_threshold":                        "innodb_read_ahead_threshold",
		"innodb_replication_delay":                           "innodb_replication_delay",
		"innodb_rollback_segments":                           "innodb_rollback_segments",
		"innodb_saved_page_number_debug":                     "innodb_saved_page_number_debug",
		"innodb_spin_wait_delay":                             "innodb_spin_wait_delay",
		"innodb_stats_auto_recalc":                           "innodb_stats_auto_recalc",
		"innodb_stats_include_delete_marked":                 "innodb_stats_include_delete_marked",
		"innodb_stats_method":                                "innodb_stats_method",
		"innodb_stats_on_metadata":                           "innodb_stats_on_metadata",
		"innodb_stats_persistent":                            "innodb_stats_persistent",
		"innodb_stats_persistent_sample_pages":               "innodb_stats_persistent_sample_pages",
		"innodb_stats_sample_pages":                          "innodb_stats_sample_pages",
		"innodb_stats_transient_sample_pages":                "innodb_stats_transient_sample_pages",
		"innodb_status_output":                               "innodb_status_output",
		"innodb_status_output_locks":                         "innodb_status_output_locks",
		"innodb_strict_mode":                                 "innodb_strict_mode",
		"innodb_support_xa":                                  "innodb_support_xa",
		"innodb_sync_spin_loops":                             "innodb_sync_spin_loops",
		"innodb_table_locks":                                 "innodb_table_locks",
		"innodb_thread_concurrency":                          "innodb_thread_concurrency",
		"innodb_thread_sleep_delay":                          "innodb_thread_sleep_delay",
		"innodb_tmpdir":                                      "innodb_tmpdir",
		"innodb_trx_purge_view_update_only_debug":            "innodb_trx_purge_view_update_only_debug",
		"innodb_trx_rseg_n_slots_debug":                      "innodb_trx_rseg_n_slots_debug",
		"innodb_undo_log_truncate":                           "innodb_undo_log_truncate",
		"innodb_undo_logs":                                   "innodb_undo_logs",
		"interactive_timeout":                                "interactive_timeout",
		"internal_tmp_disk_storage_engine":                   "internal_tmp_disk_storage_engine",
		"join_buffer_size":                                   "join_buffer_size",
		"keep_files_on_create":                               "keep_files_on_create",
		"key_buffer_size":                                    "key_buffer_size",
		"key_cache_age_threshold":                            "key_cache_age_threshold",
		"key_cache_block_size":                               "key_cache_block_size",
		"key_cache_division_limit":                           "key_cache_division_limit",
		"keyring_aws_cmk_id":                                 "keyring_aws_cmk_id",
		"keyring_aws_region":                                 "keyring_aws_region",
		"keyring_encrypted_file_data":                        "keyring_encrypted_file_data",
		"keyring_encrypted_file_password":                    "keyring_encrypted_file_password",
		"keyring_file_data":                                  "keyring_file_data",
		"keyring_okv_conf_dir":                               "keyring_okv_conf_dir",
		"keyring_operations":                                 "keyring_operations",
		"lc_messages":                                        "lc_messages",
		"lc_time_names":                                      "lc_time_names",
		"local_infile":                                       "local_infile",
		"lock_wait_timeout":                                  "lock_wait_timeout",
		"log_backward_compatible_user_definitions":           "log_backward_compatible_user_definitions",
		"log_bin_trust_function_creators":                    "log_bin_trust_function_creators",
		"log_builtin_as_identified_by_password":              "log_builtin_as_identified_by_password",
		"log_error_verbosity":                                "log_error_verbosity",
		"log_output":                                         "log_output",
		"log_queries_not_using_indexes":                      "log_queries_not_using_indexes",
		"log_slow_admin_statements":                          "log_slow_admin_statements",
		"log_slow_slave_statements":                          "log_slow_slave_statements",
		"log_statements_unsafe_for_binlog":                   "log_statements_unsafe_for_binlog",
		"log_syslog":                                         "log_syslog",
		"log_syslog_facility":                                "log_syslog_facility",
		"log_syslog_include_pid":                             "log_syslog_include_pid",
		"log_syslog_tag":                                     "log_syslog_tag",
		"log_throttle_queries_not_using_indexes":             "log_throttle_queries_not_using_indexes",
		"log_timestamps":                                     "log_timestamps",
		"log_warnings":                                       "log_warnings",
		"long_query_time":                                    "long_query_time",
		"low_priority_updates":                               "low_priority_updates",
		"master_info_repository":                             "master_info_repository",
		"master_verify_checksum":                             "master_verify_checksum",
		"max_allowed_packet":                                 "max_allowed_packet",
		"max_binlog_cache_size":                              "max_binlog_cache_size",
		"max_binlog_size":                                    "max_binlog_size",
		"max_binlog_stmt_cache_size":                         "max_binlog_stmt_cache_size",
		"max_connect_errors":                                 "max_connect_errors",
		"max_connections":                                    "max_connections",
		"max_delayed_threads":                                "max_delayed_threads",
		"max_error_count":                                    "max_error_count",
		"max_execution_time":                                 "max_execution_time",
		"max_heap_table_size":                                "max_heap_table_size",
		"max_insert_delayed_threads":                         "max_insert_delayed_threads",
		"max_join_size":                                      "max_join_size",
		"max_length_for_sort_data":                           "max_length_for_sort_data",
		"max_points_in_geometry":                             "max_points_in_geometry",
		"max_prepared_stmt_count":                            "max_prepared_stmt_count",
		"max_relay_log_size":                                 "max_relay_log_size",
		"max_seeks_for_key":                                  "max_seeks_for_key",
		"max_sort_length":                                    "max_sort_length",
		"max_sp_recursion_depth":                             "max_sp_recursion_depth",
		"max_statement_time":                                 "max_statement_time",
		"max_tmp_tables":                                     "max_tmp_tables",
		"max_user_connections":                               "max_user_connections",
		"max_write_lock_count":                               "max_write_lock_count",
		"min_examined_row_limit":                             "min_examined_row_limit",
		"multi_range_count":                                  "multi_range_count",
		"myisam_data_pointer_size":                           "myisam_data_pointer_size",
		"myisam_max_sort_file_size":                          "myisam_max_sort_file_size",
		"myisam_repair_threads":                              "myisam_repair_threads",
		"myisam_sort_buffer_size":                            "myisam_sort_buffer_size",
		"myisam_stats_method":                                "myisam_stats_method",
		"myisam_use_mmap":                                    "myisam_use_mmap",
		"mysql_firewall_mode":                                "mysql_firewall_mode",
		"mysql_firewall_trace":                               "mysql_firewall_trace",
		"mysql_native_password_proxy_users":                  "mysql_native_password_proxy_users",
		"mysqlx-connect-timeout":                             "mysqlx-connect-timeout",
		"mysqlx_connect_timeout":                             "mysqlx_connect_timeout",
		"mysqlx-idle-worker-thread-timeout":                  "mysqlx-idle-worker-thread-timeout",
		"mysqlx_idle_worker_thread_timeout":                  "mysqlx_idle_worker_thread_timeout",
		"mysqlx-max-allowed-packet":                          "mysqlx-max-allowed-packet",
		"mysqlx_max_allowed_packet":                          "mysqlx_max_allowed_packet",
		"mysqlx-max-connections":                             "mysqlx-max-connections",
		"mysqlx_max_connections":                             "mysqlx_max_connections",
		"mysqlx-min-worker-threads":                          "mysqlx-min-worker-threads",
		"mysqlx_min_worker_threads":                          "mysqlx_min_worker_threads",
		"ndb-allow-copying-alter-table":                      "ndb-allow-copying-alter-table",
		"ndb_autoincrement_prefetch_sz":                      "ndb_autoincrement_prefetch_sz",
		"ndb_blob_read_batch_bytes":                          "ndb_blob_read_batch_bytes",
		"ndb_blob_write_batch_bytes":                         "ndb_blob_write_batch_bytes",
		"ndb_cache_check_time":                               "ndb_cache_check_time",
		"ndb_clear_apply_status":                             "ndb_clear_apply_status",
		"ndb_data_node_neighbour":                            "ndb_data_node_neighbour",
		"ndb_default_column_format":                          "ndb_default_column_format",
		"ndb_deferred_constraints":                           "ndb_deferred_constraints",
		"ndb_distribution":                                   "ndb_distribution",
		"ndb_distribution={KEYHASH|LINHASH}":                 "ndb_distribution={KEYHASH|LINHASH}",
		"ndb_eventbuffer_free_percent":                       "ndb_eventbuffer_free_percent",
		"ndb_eventbuffer_max_alloc":                          "ndb_eventbuffer_max_alloc",
		"ndb_extra_logging":                                  "ndb_extra_logging",
		"ndb_force_send":                                     "ndb_force_send",
		"ndb_fully_replicated":                               "ndb_fully_replicated",
		"ndb_index_stat_enable":                              "ndb_index_stat_enable",
		"ndb_index_stat_option":                              "ndb_index_stat_option",
		"ndb_join_pushdown":                                  "ndb_join_pushdown",
		"ndb_log_bin":                                        "ndb_log_bin",
		"ndb_log_binlog_index":                               "ndb_log_binlog_index",
		"ndb_log_empty_epochs":                               "ndb_log_empty_epochs",
		"ndb_log_empty_update":                               "ndb_log_empty_update",
		"ndb_log_exclusive_reads":                            "ndb_log_exclusive_reads",
		"ndb_log_update_minimal":                             "ndb_log_update_minimal",
		"ndb_log_updated_only":                               "ndb_log_updated_only",
		"ndb_optimization_delay":                             "ndb_optimization_delay",
		"ndb_read_backup":                                    "ndb_read_backup",
		"ndb_recv_thread_cpu_mask":                           "ndb_recv_thread_cpu_mask",
		"ndb_report_thresh_binlog_epoch_slip":                "ndb_report_thresh_binlog_epoch_slip",
		"ndb_report_thresh_binlog_mem_usage":                 "ndb_report_thresh_binlog_mem_usage",
		"ndb_show_foreign_key_mock_tables":                   "ndb_show_foreign_key_mock_tables",
		"ndb_slave_last_conflict_epoch":                      "ndb_slave_last_conflict_epoch",
		"ndb_use_exact_count":                                "ndb_use_exact_count",
		"ndb_use_transactions":                               "ndb_use_transactions",
		"ndbinfo_max_bytes":                                  "ndbinfo_max_bytes",
		"ndbinfo_max_rows":                                   "ndbinfo_max_rows",
		"ndbinfo_offline":                                    "ndbinfo_offline",
		"ndbinfo_show_hidden":                                "ndbinfo_show_hidden",
		"ndbinfo_table_prefix":                               "ndbinfo_table_prefix",
		"net_buffer_length":                                  "net_buffer_length",
		"net_read_timeout":                                   "net_read_timeout",
		"net_retry_count":                                    "net_retry_count",
		"net_write_timeout":                                  "net_write_timeout",
		"new":                                                "new",
		"offline_mode":                                       "offline_mode",
		"old_alter_table":                                    "old_alter_table",
		"old_passwords":                                      "old_passwords",
		"optimizer_prune_level":                              "optimizer_prune_level",
		"optimizer_search_depth":                             "optimizer_search_depth",
		"optimizer_switch":                                   "optimizer_switch",
		"optimizer_trace":                                    "optimizer_trace",
		"optimizer_trace_features":                           "optimizer_trace_features",
		"optimizer_trace_limit":                              "optimizer_trace_limit",
		"optimizer_trace_max_mem_size":                       "optimizer_trace_max_mem_size",
		"optimizer_trace_offset":                             "optimizer_trace_offset",
		"parser_max_mem_size":                                "parser_max_mem_size",
		"preload_buffer_size":                                "preload_buffer_size",
		"profiling":                                          "profiling",
		"profiling_history_size":                             "profiling_history_size",
		"query_alloc_block_size":                             "query_alloc_block_size",
		"query_cache_limit":                                  "query_cache_limit",
		"query_cache_min_res_unit":                           "query_cache_min_res_unit",
		"query_cache_size":                                   "query_cache_size",
		"query_cache_type":                                   "query_cache_type",
		"query_cache_wlock_invalidate":                       "query_cache_wlock_invalidate",
		"query_prealloc_size":                                "query_prealloc_size",
		"range_alloc_block_size":                             "range_alloc_block_size",
		"range_optimizer_max_mem_size":                       "range_optimizer_max_mem_size",
		"read_buffer_size":                                   "read_buffer_size",
		"read_only":                                          "read_only",
		"read_rnd_buffer_size":                               "read_rnd_buffer_size",
		"relay_log_info_repository":                          "relay_log_info_repository",
		"relay_log_purge":                                    "relay_log_purge",
		"require_secure_transport":                           "require_secure_transport",
		"rewriter_enabled":                                   "rewriter_enabled",
		"rewriter_verbose":                                   "rewriter_verbose",
		"rpl_semi_sync_master_enabled":                       "rpl_semi_sync_master_enabled",
		"rpl_semi_sync_master_timeout":                       "rpl_semi_sync_master_timeout",
		"rpl_semi_sync_master_trace_level":                   "rpl_semi_sync_master_trace_level",
		"rpl_semi_sync_master_wait_for_slave_count":          "rpl_semi_sync_master_wait_for_slave_count",
		"rpl_semi_sync_master_wait_no_slave":                 "rpl_semi_sync_master_wait_no_slave",
		"rpl_semi_sync_master_wait_point":                    "rpl_semi_sync_master_wait_point",
		"rpl_semi_sync_slave_enabled":                        "rpl_semi_sync_slave_enabled",
		"rpl_semi_sync_slave_trace_level":                    "rpl_semi_sync_slave_trace_level",
		"rpl_stop_slave_timeout":                             "rpl_stop_slave_timeout",
		"secure_auth":                                        "secure_auth",
		"server_id":                                          "server_id",
		"session_track_gtids":                                "session_track_gtids",
		"session_track_schema":                               "session_track_schema",
		"session_track_state_change":                         "session_track_state_change",
		"session_track_system_variables":                     "session_track_system_variables",
		"sha256_password_proxy_users":                        "sha256_password_proxy_users",
		"show_compatibility_56":                              "show_compatibility_56",
		"show_old_temporals":                                 "show_old_temporals",
		"slave_allow_batching":                               "slave_allow_batching",
		"slave_checkpoint_group=#":                           "slave_checkpoint_group=#",
		"slave_checkpoint_period=#":                          "slave_checkpoint_period=#",
		"slave_compressed_protocol":                          "slave_compressed_protocol",
		"slave_exec_mode":                                    "slave_exec_mode",
		"slave_max_allowed_packet":                           "slave_max_allowed_packet",
		"slave_net_timeout":                                  "slave_net_timeout",
		"slave_parallel_type":                                "slave_parallel_type",
		"slave_parallel_workers":                             "slave_parallel_workers",
		"slave_pending_jobs_size_max":                        "slave_pending_jobs_size_max",
		"slave_preserve_commit_order":                        "slave_preserve_commit_order",
		"slave_rows_search_algorithms=list":                  "slave_rows_search_algorithms=list",
		"slave_sql_verify_checksum":                          "slave_sql_verify_checksum",
		"slave_transaction_retries":                          "slave_transaction_retries",
		"slow_launch_time":                                   "slow_launch_time",
		"slow_query_log":                                     "slow_query_log",
		"slow_query_log_file":                                "slow_query_log_file",
		"sort_buffer_size":                                   "sort_buffer_size",
		"sql_auto_is_null":                                   "sql_auto_is_null",
		"sql_big_selects":                                    "sql_big_selects",
		"sql_buffer_result":                                  "sql_buffer_result",
		"sql_log_off":                                        "sql_log_off",
		"sql_mode":                                           "sql_mode",
		"sql_notes":                                          "sql_notes",
		"sql_quote_show_create":                              "sql_quote_show_create",
		"sql_safe_updates":                                   "sql_safe_updates",
		"sql_select_limit":                                   "sql_select_limit",
		"sql_slave_skip_counter":                             "sql_slave_skip_counter",
		"sql_warnings":                                       "sql_warnings",
		"storage_engine":                                     "storage_engine",
		"stored_program_cache":                               "stored_program_cache",
		"super_read_only":                                    "super_read_only",
		"sync_binlog":                                        "sync_binlog",
		"sync_frm":                                           "sync_frm",
		"sync_master_info":                                   "sync_master_info",
		"sync_relay_log":                                     "sync_relay_log",
		"sync_relay_log_info":                                "sync_relay_log_info",
		"table_definition_cache":                             "table_definition_cache",
		"table_open_cache":                                   "table_open_cache",
		"thread_cache_size":                                  "thread_cache_size",
		"thread_pool_high_priority_connection":               "thread_pool_high_priority_connection",
		"thread_pool_max_unused_threads":                     "thread_pool_max_unused_threads",
		"thread_pool_prio_kickup_timer":                      "thread_pool_prio_kickup_timer",
		"thread_pool_stall_limit":                            "thread_pool_stall_limit",
		"time_zone":                                          "time_zone",
		"timed_mutexes":                                      "timed_mutexes",
		"tmp_table_size":                                     "tmp_table_size",
		"transaction_alloc_block_size":                       "transaction_alloc_block_size",
		"tx_isolation":                                       "tx_isolation",
		"transaction_prealloc_size":                          "transaction_prealloc_size",
		"tx_read_only":                                       "tx_read_only",
		"transaction_write_set_extraction":                   "transaction_write_set_extraction",
		"unique_checks":                                      "unique_checks",
		"updatable_views_with_limit":                         "updatable_views_with_limit",
		"validate_password_check_user_name":                  "validate_password_check_user_name",
		"validate_password_dictionary_file":                  "validate_password_dictionary_file",
		"validate_password_length":                           "validate_password_length",
		"validate_password_mixed_case_count":                 "validate_password_mixed_case_count",
		"validate_password_number_count":                     "validate_password_number_count",
		"validate_password_policy":                           "validate_password_policy",
		"validate_password_special_char_count":               "validate_password_special_char_count",
		"version_tokens_session":                             "version_tokens_session",
		"wait_timeout":                                       "wait_timeout",
	}
)

// show variables
func ShowVariables(db *sql.DB) ([]Variable, error) {
	var vars []Variable

	rows, err := db.Query(StmtShowVariables)
	if err != nil {
		return []Variable{}, errors.Trace(err)
	}

	for rows.Next() {
		var tmpvar Variable

		err = rows.Scan(
			&tmpvar.Name,
			&tmpvar.Value,
		)

		if _, varvalue := GlobalDynamicVars[tmpvar.Name]; varvalue {
			tmpvar.Dynamic = "Yes"
		} else {
			tmpvar.Dynamic = "No"
		}

		if err != nil {
			continue
		}

		vars = append(vars, tmpvar)
	}
	return vars, nil
}

// set global or session dynamic variables
func SetDynamicVariables(db *sql.DB, variable_name string, variable_value string) error {

	if _, varvalue := GlobalDynamicVars[variable_name]; !varvalue {
		return errors.NotFoundf(variable_name)
	}

	Query := fmt.Sprintf(StmtSetDynamicVariables, variable_name, variable_value)

	_, err := db.Exec(Query)
	if err != nil {
		return errors.Trace(err)
	}
	return nil
}
